name: Deploy on GHCP

# Controls when the action will run.
on:
  workflow_dispatch:
<<<<<<< HEAD
  push:
    branches:
      - main
=======
  pull_request:
    branches:
      - "main"
>>>>>>> 73f1be44d49de729afb7b697c9d827045e09797e

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker-push:
    name: Deploy on GHCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build & push Docker image 🐳
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: arke-website
          tags: latest
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}